### ISSUE TITLE
CardImageDownloader instructions?

### ISSUE THREAD

**Issue by lsavage999** [WagicProject/wagic#1032]
I just removed Wagic 016 to try to go to 022.  I see that CardImageDownloader is available to help speed the image download process, but the ReadMe file in there isn't very helpful at all.  Does anyone have step by step instructions or can point me to some for this?  I've done some searching but found nothing.  I saw a previous post about moving JAR files, but I don't see any JAR files in either the Wagic download or in the program itself.

Any direction would be greatly appreciated.

**Comment by theredbaron1834** [comment]
I am a linux user, having some issues my self (it doesn't let me point to my config folder, just the install folder, not usable :( ).

However, your issue seems to be in general use?

So, you would download the downloader zip from here:https://github.com/WagicProject/wagic/releases/tag/wagic-v0.22.2

Then extract it. Go to the CardImageDownloader folder you just extracted. Double click on the "CardImageDownloader.jar". It isn't an exe your use to (amusing your on windows?), however, it is the program. It is a java cross platform thing. So as long as you have java installed, it should start.

You will get a nice little gui pop up. Click the res you want, and then where it says wagic path, click the button and point it to where Wagic is installed. Then click start downloaded, it should justwork.tm.

**Comment by lsavage999** [comment]
Thank you for the assist @theredbaron1834.  It appears to have worked, but I still don't have full card  images or thumbnails.  I'll keep hacking at it, but considering how buggy this version is, I may just roll back to 016.  Appreciate it!

**Comment by Vitty85** [comment]
Hi,

The downloader is really easy to use, i'm surprised if you are experimenting any problem. Anyway it's a java app so if you installed the JVM on your OS you should be able to run it. Be aware you have to point to your wagic install dir (where you have Res and User folder) and all the images will be automatically downloaded in the correct place.

About the image and thumb i'm really surprised you are having any issues, Which is your OS?

**Comment by Vitty85** [comment]
> I am a linux user, having some issues my self (it doesn't let me point to my config folder, just the install folder, not usable :( ).
> 
> However, your issue seems to be in general use?
> 
> So, you would download the downloader zip from here:https://github.com/WagicProject/wagic/releases/tag/wagic-v0.22.2
> 
> Then extract it. Go to the CardImageDownloader folder you just extracted. Double click on the "CardImageDownloader.jar". It isn't an exe your use to (amusing your on windows?), however, it is the program. It is a java cross platform thing. So as long as you have java installed, it should start.
> 
> You will get a nice little gui pop up. Click the res you want, and then where it says wagic path, click the button and point it to where Wagic is installed. Then click start downloaded, it should justwork.tm.

Which version of Linux Wagic are you using? X11 or QT? What do you mean with "I cannot use my User Folder? Is it placed in Wagic Folder same level as Res? for me it's working fine, so strange...
