### ISSUE TITLE
Card image downloader can not download to ~/.Wagic

### ISSUE THREAD

**Issue by theredbaron1834** [WagicProject/wagic#1033]
I just updated Wagic on the Arch AUR, and was looking at adding the card image downloader. However, it doesn't work well when Wagic is "installed" vs portable. The "user" doesn't have write access to install folders, however the downloader "needs" to see the "res" folder to know where to install sets at. ~/.Wagic has the "sets" folder, but it isn't read as a usable install folder.

I understand the ease of use for Win to just tell people to point to the install folder, but is there anyway to make it doable to point straight to the "sets" folder as well?

**Comment by Vitty85** [comment]
Hi,

I guess i cannot understand your problem, i tried my downloader in Windows, Android and Linux without any problem, can you give me more details about your OS and your error?

Thanks.

**Comment by Vitty85** [comment]
> I just updated Wagic on the Arch AUR, and was looking at adding the card image downloader. However, it doesn't work well when Wagic is "installed" vs portable. The "user" doesn't have write access to install folders, however the downloader "needs" to see the "res" folder to know where to install sets at. ~/.Wagic has the "sets" folder, but it isn't read as a usable install folder.
> 
> I understand the ease of use for Win to just tell people to point to the install folder, but is there anyway to make it doable to point straight to the "sets" folder as well?

Which version of Linux Wagic are you using? X11 or QT?

For X11 version the User folder is created by default in the executable folder at same level as Res (so no problem for Downloader).

For QT version the User folder is created by default in the Linux home folder with name of ".Wagic", so all you have to do is simply create a soft link named User (at same level of Res) pointing to the .Wagic folder in your Linux home, in few words, basically you have to type: "ln -s ~/.Wagic User" in the folder which contains the executable file and the Res Folder). In this way it should work just as the X11 version since the User folder will be read by game and by Downloader at same level of Res.

Let me know if you solve in this way.

**Comment by theredbaron1834** [comment]
I just created a user folder and copied, but yeah, that would work too. :)

**Comment by Vitty85** [comment]
> I just created a user folder and copied, but yeah, that would work too. :)

As you prefer of course, but with link you avoid to keep duplicated folders and files, so i reccomend that solution.

Btw i'm closing this issue, see you soon.
