### ISSUE TITLE
Some cards doesnt work properly

### ISSUE THREAD

**Issue by luisguerin** [WagicProject/wagic#1034]
Obelisk spider are putting counters on itself instead of the creature that battles it.
Forerunner of the legion doesnt put the Card on top of library.
Moment of Triumph doesnt activate at all.
Oathswoen Vampire cant summon from grave.
Thanks for the game, its really great.

**Comment by Vitty85** [comment]
Hi,

Thanks for the report, i just fixed those cards and they will be available on next 0.22.3 version coming in June.

**Comment by luisguerin** [comment]
Thanks, there are some other errors, i dont remember at the moment, but
cards with rebound arent working.
Thanks again for this game, its really fantastic.


Em qua, 27 de mai de 2020 05:13, Vittorio Alfieri <notifications@github.com>
escreveu:

**Comment by Vitty85** [comment]
I will take a look on rebound too, for the other errors open a new issue and if it's possible write the name of the broken primitives.

See you soon.

**Comment by Vitty85** [comment]
Hi,

I solved rebound problem too, now they are working correctly in this way:

1. When you cast a card with rebound from your hand it resolves and then it goes to exile.

2. Just at the beginning of your next turn you can decide to cast it again without paying its mana cost from exile.

3. If you cast it in this way the card goes from exile to graveyard, otherwise it will stay in exile and you will be not able to cast it again in next turns since rebound ability works just one time.

The fix will be available on next 0.22.3 version coming in June.
