### ISSUE TITLE
wagic app crashes immediately

### ISSUE THREAD

**Issue by superbadra** [WagicProject/wagic#1073]
downloaded apk, installed successfully, wont open, message: unfortunately, wagic has stopped

**Comment by Vitty85** [comment]
I personally tested the APK, probably is due to your device... Which model of Android are you using? We tested on several Samsung models without any problem.

See you.

**Comment by superbadra** [comment]
Thankyou,
you are correct, apologies.
My tablet is a samsung tab 4 sm-t 530
and updates only up to android version 5.0.2
I didnt notice android version compatability on the repository readme.md description.

**Comment by Vitty85** [comment]
Hi,

No need to apologies, anyone can ask support in case of problem. By the way, the minimum version i tested is Android 8.

Actually i set the SDK API level compatibility range from 10 to 29 which means that the devices should be compatible from Android 2.3.3 up to Android 10, but i cannot assure since i don't have such old devices to test.

For now i will close the issue, see you.
