### ISSUE TITLE
Muxus, Goblin Grandee (Jumpstart) Not putting Goblins in anymore

### ISSUE THREAD

**Issue by SpartaGus423** [WagicProject/wagic#1089]
**Describe the bug**
When you cast Muxus, Goblin Grandee it just says "put back" even though there is a bunch of Goblins on top and it doesn't put them in play.

**To Reproduce**
1. Cast Muxus, Goblin Grandee
2. Shows top six cards and the pop up says "Put Back" without putting any of them in play

**Expected behavior**
Cast Muxus, Goblin Grandee, Reveal top 6 cards and put all Goblin cards into play.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 x64 22H2 v.19045.2965
 - Chrome
 - Version 113.0.5672.127

**Smartphone (please complete the following information):**

**Additional context**
Not sure if this is where I post the bugs since the Wagic Forums are down.  I am also using the latest Wagic v0.24.0 for Windows posted 1 hour ago. Muxus was working 3 version before not quite sure what happened.

**Comment by Vitty85** [comment]
I guess the card code is wrong… it will be fixed in next release, meanwhile you can try this version:

[card]
name=Muxus, Goblin Grandee
aicode=activate all(creature[goblin&manacost<=5&zpos<=6]|mylibrary) moveto(mybattlefield) and!( all(*[zpos<=6]|mylibrary) bottomoflibrary )!
auto=name(Look top 6) reveal:6 optionone name(Get goblins) target(<6>creature[goblin&manacost<=5]|reveal) moveto(ownerlibrary) and!( becomes(tobecast) ueot )! optiononeend optiontwo name(put back) target(<1>*|reveal) bottomoflibrary and!( all(*|reveal) bottomoflibrary )! optiontwoend afterrevealed all(tobecast|mylibrary) moveto(ownerlibrary) and!( moveto(ownerbattlefield) )! afterrevealedend revealend
auto=_ATTACKING_name(Get 1/1 for each other goblin) type:goblin:mybattlefieldminus1minusend/type:goblin:mybattlefieldminus1minusend ueot
text=When Muxus, Goblin Grandee enters the battlefield, reveal the top six cards of your library. Put all Goblin creature cards with mana value 5 or less from among them onto the battlefield and the rest on the bottom of your library in a random order. -- Whenever Muxus attacks, it gets +1/+1 until end of turn for each other Goblin you control.
mana={4}{R}{R}
type=Legendary Creature
subtype=Goblin Noble
power=4
toughness=4
[/card]

see you.

**Comment by SpartaGus423** [comment]
Thanks will try it..Sorry if this wasn't the place to post the bugs I just didn't know where to post.  I love the game and love playing it.  Thanks for everything.

**Comment by Vitty85** [comment]
Hi, you can join the discord Chanel here:A New Way to Chat with Friends & Communitiesdiscord.ggSee you.--Inviato da iPhoneIl giorno 22 mag 2023, alle ore 23:45, SpartaGus423 ***@***.***> ha scritto:﻿
Thanks will try it..Sorry if this wasn't the place to post the bugs I just didn't know where to post.  I love the game and love playing it.  Thanks for everything.

**Comment by Vitty85** [comment]
Closed in last update of Wagic 0.24.0, you can download again in latest release page.

See you.
