### ISSUE TITLE
Cannot find mana objects with "&&" in their ability

### ISSUE THREAD

**Issue by kevlahnota** [WagicProject/wagic#700]
To reproduce: have Grand Coliseum in play then play Reflecting Pool, Try to tap Reflecting Pool, nothing happens. But if you have Mana Confluence instead of Grand Coliseum and play Reflecting Pool, Reflecting Pool works fine.
![1t](http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=382967&type=card)![2](http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=382342&type=card)![3](http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=380453&type=card)

**Comment by zethfoxster** [comment]
this one is tricky kev, it deals with ability nesting, i am willing to bet it extends into all land mana abilities that are nested. 
safest and easiest fix for this would be a adding a tag ability and fixing it on a card to card basis. 
something like auto=canproduce({G}{R}{W}). then instead of making an ability, it simply sets your source card pland*color* by going into a function abilityfactory::getmyproduction{ if string find G card->plandg = 1;}....im sure you catch my drift.

there are a hand full of abilities that you just cant get thier nested, &&, transforms(,newability, Ability$!...basically the super classes.

**Comment by zethfoxster** [comment]
you can also have pland*type* set during the parse of "add{"

**Comment by kevlahnota** [comment]
closing this, I replaced all add{mana} && ability to use add{mana} and!(ability)! on commit #936 , as long as we use andAbility with mana producer, then there will be be no problem parsing them with canproducemana function
