### ISSUE TITLE
Deck Editor images

### ISSUE THREAD

**Issue by MagicMaxcer** [WagicProject/wagic#764]
With your loaded images when you go in the deck editor the cards are blurry while in the trophy they are not?....this seam like a small bug that can be fix also fix the back end of the card when it flips is also blurry in the deck editor thnx

**Comment by kevlahnota** [comment]
What version do you use?
![blurry](http://i44.photobucket.com/albums/f1/kevlahnota/ba539cc2-afbc-4b03-8103-ddbaf3d923f9_zpslrkdieyl.png)

**Comment by MagicMaxcer** [comment]
I'm using the current masters version which is the psp version 0.19.2.1179

**Comment by zethfoxster** [comment]
This is a limitation of psp systems younger than vita. Vita has the ability to run hires. Anything younger, while still kept in our support, is not something we can correct.

Kev has attempted multiple methods of making psp 1000-3000 run better, or deck editor run with normal quads. And it boils down to psp system being 12 years old.

This is unfortunately something we can not keep focusing on moving forward. Sorry.

If you can confirm this is using psp vita, ill reopen otherwise closing this ticket as a nonrepair.
