### ISSUE TITLE
Wagic Windows 10 wont boot up

### ISSUE THREAD

**Issue by yuyu63** [WagicProject/wagic#972]
I recently downloaded the unoffical and 0.20.01, 0.19.x and then the 0.18.6 versions of wagic and neather boot up on my 64-bit Windows 10 OS i opened my VM-ware with xp pro on it and it runs all copies fine, i am on an alienware 14 laptop running Win 10 creators update version 10.0.15063 i reinstalled both 32 and 64 bit versions of C++ redistrubtable 2010, i am unshure if this is a issue with the creator update or win10 needs its own version of wagic.

**Comment by kevlahnota** [comment]
can you try this private build(added support for Amonkhet Mechanics) if this works on your end: https://mega.nz/#!115WAAIb!y02WmEdDCCcr7nBFcjX0faVwKTHwhJ69gQk-ALvn55o

**Comment by yuyu63** [comment]
While this is showing up in tank manager witch means my event viewer can trace a log...
---------------------------------------------------------------------------------------------
Faulting application name: Wagic.exe, version: 0.0.0.0, time stamp: 0x59821a5a
Faulting module name: ntdll.dll, version: 10.0.15063.447, time stamp: 0xd51d5c5e
Exception code: 0xc0000374
--------------------------------------------------------------------------------------------
Does that help?

**Comment by kevlahnota** [comment]
you have similar error I found in the forums: http://wololo.net/forum/viewtopic.php?f=12&t=3712 but I don't know what is the suggested solution for that, sorry.

**Comment by yuyu63** [comment]
NTdll.dll as it turns out is a file that shows failer in hardware equipment, while a system check comes clean.

**Comment by Rolzad73** [comment]
@yuyu63 I just downloaded the last "latest-master" Wagic-windows.zip (commit 07e6d90c9858b041361e8659eb2937e8ec30e2cb)

and simply extracted them on the desktop and ran them. Win 10 pro x64, seemed to work fine.

Although this is my work laptop, with lots of developer tools installed, including Visual Studio 2017, so I probably have all the dependencies without knowing exactly what.

**Comment by Xirious** [comment]
Has anyone managed to figure out why this isn't working? I've tried all the links in this thread and nothing seems to be working. I'd really like to play the latest and greatest of Wagic.

**Comment by kevlahnota** [comment]
@Xirious  can you try my unofficial build here: https://mega.nz/#!115WAAIb!y02WmEdDCCcr7nBFcjX0faVwKTHwhJ69gQk-ALvn55o

**Comment by Xirious** [comment]
@kevlahnota Thank you but like I said I've tried all the links in this thread and all the installs on the releases page. Nothing is working. But some insight might help - I'm 100% certain something is missing from my PC because I try that exact same build on my other PC where I've done quite a bit of development including having Visual Studio there and it works. I'd just like to know what exactly is missing so I can install that. 

Side note I've tried CMD -> sfc /scannow to see if it is broken and it's not from Window's perspective.

**Comment by Rolzad73** [comment]
@Xirious I re-attempted an install, this time on my home setup of Win 10 Home x64, of the latest-master, which has absolutely no development software on it as I use it only for Steam gaming, and the it seemed to work no problem.

Not that I am discounting your account of the error, but I can not see why it would not work for you.  Of course, we must have different environments.

Kindly I propose to you, if you have development knowledge, maybe you can supply logs of the error, in whatever form you think is applicable.  As well, Wagic is an open project, and always welcoming of new developers to solve problems to help make WTH the best version of the card game available.

Clone, compile, debug.  The wiki instructions should at least get you started even if they might be slightly outdated.

**Comment by Xirious** [comment]
@Rolzad73 Thanks for this. This gives me an idea... I have a feeling it's got to do with one of the updates installed because of the Creator's Update version I have on my Windows 10 Pro. I reinstalled that PC from scratch this past weekend with an ISO that has the Creators Update with it. 

I figure it's one of the updates installed by Windows in a similar vein to the same problem I'm having with another program which causes a "Faulting module name: KERNELBASE.dll" error but that [can be fixed if you remove a certain update from Windows](https://www.youtube.com/watch?v=kdstd8OPeqU). Seeing, however, that I currently have the Creators Update I can't remove that specific update and am stuck with that KERNELBASE problem. It fails in a very similar way to my Wagic (no error message, only viewable in Event viewer) so feel it might be a similar problem to what I'm experiencing with Wagic. _If_ this is something similar it would require reinstalling from fresh with a lower version of Windows 10 and checking which updates break it. Not sure I want to exactly go down that path if it might not even be the error. 

As for logs I could supply the logs from the Windows Event viewer but I'm uncertain what other ways of catching/tracing that error might be available. The error is not the normal Windows error in that it does not pop up with a Window saying "Wagic has failed... etc." with details and can only be viewed on the Windows Event Viewer. Maybe you might be able suggest another way to trace this error? 

I'd like to keep that specific PC free of development installs if possible. I have a work Ubuntu/Mint machine but I hardly think that'll help here. I might reinstall again this weekend and if that is the case I'll first install VSCode and compile it/test it out and then I'll try it with lower version of Windows and see if the issue is alleviated on a fresh, pre-Creators Update PC.  

Speaking of contributing, I've been contemplating that for a while now but I'm not quite sure I have the free time available just yet. I'll keep my eye on it though and see if I can add something in somewhere.

**Comment by yuyu63** [comment]
After revisiting this almost a year later i have found the issue is not with win 10 OS but with the integrated graphics drivers never even thinking of needing the Nvidia card i try6ed it on a desire to play this again and it works grate. just wanted to update this is now running fine and letting people know its solved
